#!/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for i in $@; do
    echo "PYTHONPATH=\$PWD python good_models/model_$i.py" | \
	python $DIR/submit.py --name model_$i \
	       --datapath /home2/ift6ed20/datasets/mlp_dataset.h5
done 
